### ISSUE TITLE
change color on search box when phrase not found

### ISSUE THREAD

**Issue by jvoxels** [Quicksaver/FindBar-Tweak#176]
Currently it comes up a very light pink, I'd like to change it to a darker color.  Ideas?  thanks

**Comment by Quicksaver** [comment]
The background color of the textbox really shouldn't be that light, it's pink yeah but it should be a somewhat strong pink. You may have some theme or stylesheet affecting it without knowing (or your screen's colors may not be properly calibrated, you may want to re-check that).

However, you can change the color easily with Styilsh with a stylesheet like the following:
```CSS
.findbar-textbox[status="notfound"] {
  background-color: #000000 !important; /* background color */
  color: #DD7700 !important; /* text color */
}
```

Just change the values to whatever suits you better. I'm closing this issue as it's not really pertinent to the add-on, but you can still reply here so let me know if you need any more extra help.
