### ISSUE TITLE
Compatibility with (Complete) Themes

### ISSUE THREAD

**Issue by Quicksaver** [Quicksaver/FindBar-Tweak#22]
**Position of the FindBar**

Placement of the FindBar on top of the browser window should be accurate with most themes, if it is not please open a new issue about it.

**Background Themes**

Background themes (formerly known as Personas) should be already fully supported, with the background image continuing in the background of the FindBar. If this isn't the case then please also open a new issue about it. Note that the rounded corners don't appear with personas, because it's impossible to correctly apply the background image to them as they are right now. This is known and may or may not be fixed in the future.

**Complete Themes Compatibility**

For appearance issues, such as odd colors in the Findbar while using some themes, or the highlights grid not properly styled when the look of the scrollbars is changed, or anything similar, please before anything, try to contact the developer of the theme and ask them to add support for these features. You can point them to the **For Theme Developers** section below in this thread.

You must understand that it's impossible for me to try out every single theme out there and change the FindBar to support it, especially when I'm not familiar with these themes and don't know how they should actually look like. It's a much easier task to do on the theme's side.

If you can't contact the theme developer, or there's a more serious problem, please let me know by opening a new issue or posting a new comment in this thread and I'll see what I can do to ensure compatibility with any specific theme.

**For Theme Developers**

To style the FindBar on top is very easy, you just need to override these CSS declarations and any others that may be required. Please don't touch the _position_, _overflow_, _top_, _left_, _right_ and _max-width_ properties as they are used for the placement of the FindBar. _The same properties and values should be set on **#findbartweak-findInTabs-box[movetotop]** except for the border-left and border-right which should be set to none._ Don't forget the FindBar in the view source window, if it's supposed to be styled there then make sure it is properly so, if it's not then try adding a _#main-window_ selector in every declaration:

``` CSS
/* All OS's */
findbar[movetotop] {
    border-top: none;
    border-radius: 0 0 8px 8px;
}

/* Windows */
findbar[movetotop]:not([inPDFJS]) {
    background-color: -moz-dialog; /* Windows XP */
    background-color: rgb(219,234,249); /* Windows Vista/7 and above */
    border-bottom: 1px solid rgb(0,0,0);
    border-right: 1px solid rgb(0,0,0);
    border-left: 1px solid rgb(0,0,0);
    -moz-border-bottom-colors: ThreeDShadow;
    -moz-border-right-colors: ThreeDShadow;
    -moz-border-left-colors: ThreeDShadow;
}

/* Linux */
findbar[movetotop]:not([inPDFJS]) {
    background-color: -moz-dialog;
    border-bottom: 1px solid rgb(0,0,0);
    border-right: 1px solid rgb(0,0,0);
    border-left: 1px solid rgb(0,0,0);
    -moz-border-bottom-colors: ThreeDShadow;
    -moz-border-right-colors: ThreeDShadow;
    -moz-border-left-colors: ThreeDShadow;
}

/* Max OS X */
findbar[movetotop]:not([inPDFJS]) {
    background-color: -moz-mac-chrome-active;
    border-bottom: 1px solid rgba(0,0,0,0.57);
    border-right: 1px solid rgba(0,0,0,0.57);
    border-left: 1px solid rgba(0,0,0,0.57);
    -moz-border-bottom-colors: rgba(0,0,0,0.57);
    -moz-border-right-colors: rgba(0,0,0,0.57);
    -moz-border-left-colors: rgba(0,0,0,0.57);
}
findbar[movetotop]:not([inPDFJS]):-moz-window-inactive {
    background-color: -moz-mac-chrome-inactive;
    border-bottom: 1px solid rgba(0,0,0,0.32);
    border-right: 1px solid rgba(0,0,0,0.32);
    border-left: 1px solid rgba(0,0,0,0.32);
    -moz-border-bottom-colors: rgba(0,0,0,0.32);
    -moz-border-right-colors: rgba(0,0,0,0.32);
    -moz-border-left-colors: rgba(0,0,0,0.32);
}
```

If you're also styling the PDF.JS window, then simply add the equivalent **findbar[movetotop][inPDFJS]** selectors with the appropriate properties, like above.

In every case, override these for the rounded outwards corners, the ones that "connect" to the top of the browser. Don't touch _margin-left_ or _margin-right_ in these; adjust the _box-shadow_ offsets and values as needed if you change _border-radius_ and the _height_ and _width_ values (these are for Windows 7 but they work the same way for every OS only with different values):

``` CSS
findbar[movetotop]:before,
findbar[movetotop]:after {
    width: 16px;
    height: 16px;
    border-radius: 50%;
}
findbar[movetotop]:not([inPDFJS]):-moz-locale-dir(ltr):before,
findbar[movetotop]:not([inPDFJS]):-moz-locale-dir(rtl):after {
    box-shadow:     2px -2px 0 -2px rgb(170,188,207), /* FindBar's border color */
                    7px -4px 0px -4px rgb(219,234,249), /* FindBar's background color */
                    6px -4px 0px -4px rgb(219,234,249); /* FindBar's background color */
}
findbar[movetotop]:not([inPDFJS]):-moz-locale-dir(ltr):after,
findbar[movetotop]:not([inPDFJS]):-moz-locale-dir(rtl):before {
    box-shadow:     -2px -2px 0 -2px rgb(170,188,207), /* FindBar's border color */
                    -7px -4px 0px -4px rgb(219,234,249), /* FindBar's background color */
                    -6px -4px 0px -4px rgb(219,234,249); /* FindBar's background color */
}
```

To adjust the highlights grid in the case your theme or add-on changes the appearance of the scrollbars, simply override these values (these are for Windows 7 but they work the same way for every OS only with different values):

``` CSS
vbox[anonid="findGrid"] {
    -moz-margin-start: 2px; /* Distance from the actual window margin, 0px will go all way to the right */
    width: 13px; /* Will increase or decrease on the left */
}
vbox[anonid="findGrid"]:not([gridSpacers="none"]) vbox.topSpacer[flex="0"],
vbox[anonid="findGrid"][gridSpacers="single"] vbox.bottomSpacer[flex="0"] {
    height: 18px; /* Size of the normal up and down scrollbar buttons */
}
vbox[anonid="findGrid"][gridSpacers="double"] vbox.bottomSpacer[flex="0"] {
    height: 36px; /* Size of the bottom scrollbar buttons if horizontal scrollbar is visible, to account for the extra empty space below, add the hscrollbar's height */
}
```

For the highlights grid in frames, just add a **div[ownedbyfindbartweak][anonid="gridBox"]** to the above declarations, and replace all the vbox's for div's. Also, note that these are added into the content document itself, so you can't use these inside a **@-moz-document { }** block! Again, these are for Windows 7, but the declarations are the same for all OS's only with different values.

``` CSS
div[ownedbyfindbartweak][anonid="gridBox"] div[anonid="findGrid"] {
    -moz-margin-start: 2px; /* Distance from the actual window margin, 0px will go all way to the right */
    width: 13px; /* Will increase or decrease on the left */
}
div[ownedbyfindbartweak][anonid="gridBox"] div[anonid="findGrid"]:not([gridSpacers="none"]) div.topSpacer[flex="0"],
div[ownedByFindBarTweak][anonid="gridBox"] div[anonid="findGrid"][gridSpacers="single"] div.bottomSpacer[flex="0"] {
    height: 18px; /* Size of the normal up and down scrollbar buttons */
}
div[ownedbyfindbartweak][anonid="gridBox"] div[anonid="findGrid"][gridSpacers="double"] div.bottomSpacer[flex="0"] {
    height: 36px; /* Size of the bottom scrollbar buttons if horizontal scrollbar is visible, to account for the extra empty space below, add the hscrollbar's height */
}
```
