### ISSUE TITLE
Code to remove "PHRASE NOT FOUND"

### ISSUE THREAD

**Issue by BarbieBarb** [Quicksaver/FindBar-Tweak#252]
You gave me this code snippet a couple years ago to color the "1 of 2 matches" but remove the
"Phrase not Found" which is unessessary clutter, and which I did not need as the textbox turns red and that is enough warning for me.
The code .findbar-find-status:not([counter]) does not work anymore with this latest version.
Could you please tell me what code will work now please?
Please and Thankyou

/* "1 OF 2 MATCHES"*/
.findbar-find-fast.findbar-find-status
{color: red !important;}
/* REMOVES "PHRASE NOT FOUND" BUT NOT REMOVE "1 OF 2 MATCHES" */
.findbar-find-status:not([counter]) 
{color: transparent !important;}

**Comment by Quicksaver** [comment]
Indeed there isn't a way to do that with CSS only right now. I'll see what I can do about it.

**Comment by BarbieBarb** [comment]
Thankyou very much for trying to find a method for this. 
Fingers Crossed.

**Comment by Gitoffthelawn** [comment]
Can you add a class or identifier, or something else that can be selected with CSS so that custom CSS can be written to modify the color/visibility of the messages?

I'm thinking something to differentiate "Phrase not found" from "1 of 2 matches", and those strings from other strings.

**Comment by Quicksaver** [comment]
Turns out it is actually still possible to do this through CSS:
```CSS
/* Don't show "Phrase not found" but show counter if there are matches */
findbar image[anonid="find-status-icon"][status="notfound"] + description[anonid="find-status"] {
  visibility: collapse;
}
```

And it's also possible to distinguish through CSS alone when the find wraps as well:
```CSS
/* Color the counter green when page find wraps */
findbar image[anonid="find-status-icon"][status="wrapped"] + description[anonid="find-status"] {
  color: green;
}
```
